before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install imagemagick libmagic; fi
    #  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y imagemagick; fi

language: c
os:
  # - linux
  - osx
    #dist: bionic

compiler: clang
script: make
