before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install imagemagick libmagic; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; wget https://www.imagemagick.org/download/ImageMagick.tar.gz; tar xvzf ImageMagick.tar.gz; cd ImageMagick-7*; ./configure; make; sudo make install; sudo ldconfig /usr/local/lib; fi

language: c
os:
  - linux
  - osx
dist: bionic

compiler: clang
script: make
