before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt install -y imagemagick; fi

language: c
os:
  - linux
  - osx
compiler: clang
script: make
