name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install ImageMagick > 7 from source
      run: |
          wget https://www.imagemagick.org/download/ImageMagick.tar.gz
          tar xvzf ImageMagick.tar.gz && cd ImageMagick-7*
          pwd
          ./configure
          make && sudo make install
          sudo ldconfig /usr/local/lib
          sudo apt install libmagic
    - name: make Terminal Image
      run: make
